version: '3.9'

services:
  db:
    container_name: goly-server
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "db"
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdb:/var/lib/postgresql/data